[package]
name = "bundler"
version = "0.1.0"
authors = ["Slava Shklyaev <slava@slava.sh>"]
description = "Creates a single-source-file version of a Cargo package."
documentation = "https://docs.rs/bundler"
homepage = "https://github.com/slava-sh/rust-bundler"
repository = "https://github.com/slava-sh/rust-bundler"
keywords = ["single-file", "bundle", "merge", "expand", "cli"]
categories = ["command-line-utilities"]
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "slava-sh/rust-bundler" }
codecov = { repository = "slava-sh/rust-bundler" }

[[bin]]
name = "bundle"
path = "src/main.rs"

[dependencies]
quote = "0.5.1"
rustfmt = "0.10.0"
syn = { version = "0.13.1", features = ["full", "extra-traits", "visit-mut"] }
toml = "0.4.6"

[dev-dependencies]
goldenfile = "0.5.1"
