[package]
name = "bundler"
version = "0.1.0"
authors = ["Slava Shklyaev <slava@slava.sh>"]

[dependencies]
quote = "0.5.1"
syn = { version = "0.13.1", features = ["full", "extra-traits", "visit-mut"] }
toml = "0.4.6"
