[package]
name = "bundler"
version = "0.1.0"
authors = ["Slava Shklyaev <slava@slava.sh>"]

[[bin]]
name = "bundle"
path = "src/main.rs"

[dependencies]
quote = "0.5.1"
syn = { version = "0.13.1", features = ["full"] }
toml = "0.4.6"

[dev-dependencies]
goldenfile = "0.5.1"
